//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaNomina.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstadoCivil
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EstadoCivil()
        {
            this.Empleados = new HashSet<Empleados>();
        }
    
        public int id_estado_civil { get; set; }
        public string nombre { get; set; }

        public Nullable<System.DateTime> fecha_creacion { get; set; }        // ← AGREGAR ESTA LÍNEA
        public Nullable<System.DateTime> fecha_actualizacion { get; set; }   // ← AGREGAR ESTA LÍNEA


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Empleados> Empleados { get; set; }
    }
}
