//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
namespace SistemaNomina.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Notificaciones
    {
        public int id_notificacion { get; set; }
        public Nullable<int> id_remitente { get; set; }
        public int id_destinatario { get; set; }
        public string titulo { get; set; }
        public string mensaje { get; set; }
        public string tipo { get; set; }
        public Nullable<int> referencia_id { get; set; }
        public string referencia_tipo { get; set; }
        public bool leido { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_leido { get; set; }
        public string prioridad { get; set; }
        public string icono { get; set; }
        public string color { get; set; }

        public virtual Empleados Empleados { get; set; } // Remitente
        public virtual Empleados Empleados1 { get; set; } // Destinatario

        // Propiedades calculadas
        [NotMapped]
        public string TiempoTranscurrido
        {
            get
            {
                var diferencia = DateTime.Now - fecha_creacion;

                if (diferencia.TotalMinutes < 1)
                    return "Hace un momento";
                else if (diferencia.TotalMinutes < 60)
                    return $"Hace {(int)diferencia.TotalMinutes} minutos";
                else if (diferencia.TotalHours < 24)
                    return $"Hace {(int)diferencia.TotalHours} horas";
                else if (diferencia.TotalDays < 7)
                    return $"Hace {(int)diferencia.TotalDays} días";
                else
                    return fecha_creacion.ToString("dd/MM/yyyy");
            }
        }

        [NotMapped]
        public string ClasePrioridad
        {
            get
            {
                switch (prioridad)
                {
                    case "urgente": return "priority-urgent";
                    case "alta": return "priority-high";
                    case "normal": return "";
                    case "baja": return "priority-low";
                    default: return "";
                }
            }
        }

        [NotMapped]
        public Empleados Remitente
        {
            get { return Empleados; }
            set { Empleados = value; }
        }

        [NotMapped]
        public Empleados Destinatario
        {
            get { return Empleados1; }
            set { Empleados1 = value; }
        }
    }
}