//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaNomina
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notificaciones
    {
        public int id_notificacion { get; set; }
        public int id_destinatario { get; set; }
        public Nullable<int> id_remitente { get; set; }
        public string titulo { get; set; }
        public string mensaje { get; set; }
        public string tipo { get; set; }
        public string prioridad { get; set; }
        public Nullable<bool> leido { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_leido { get; set; }
        public string referencia_tipo { get; set; }
        public Nullable<int> referencia_id { get; set; }
        public string icono { get; set; }
        public string color { get; set; }
        public string TiempoTranscurrido { get; set; }
    
        public virtual Empleados Empleados { get; set; }
        public virtual Empleados Empleados1 { get; set; }
    }
}
